openapi: 3.1.0
info:
  title: Atrarium Feed Generator API
  description: AT Protocol-compliant Feed Generator API for Atrarium community management system
  version: 1.0.0
  contact:
    name: Atrarium Project
  license:
    name: MIT

servers:
  - url: https://atrarium.example.com
    description: Production server
  - url: http://localhost:8787
    description: Local development (Miniflare)

tags:
  - name: AT Protocol
    description: AT Protocol Feed Generator specification endpoints
  - name: Service Discovery
    description: DID document and service discovery

paths:
  /.well-known/did.json:
    get:
      summary: Get DID document
      description: Returns the DID document identifying this Feed Generator service (AT Protocol requirement)
      operationId: getDIDDocument
      tags:
        - Service Discovery
        - AT Protocol
      responses:
        '200':
          description: DID document successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DIDDocument'
              example:
                '@context': ['https://www.w3.org/ns/did/v1']
                id: 'did:web:atrarium.example.com'
                service:
                  - id: '#bsky_fg'
                    type: 'BskyFeedGenerator'
                    serviceEndpoint: 'https://atrarium.example.com'
          headers:
            Cache-Control:
              schema:
                type: string
              description: Cache control header
              example: 'public, max-age=3600'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /xrpc/app.bsky.feed.describeFeedGenerator:
    get:
      summary: Describe feed generator
      description: Returns metadata about available feeds from this generator (AT Protocol requirement)
      operationId: describeFeedGenerator
      tags:
        - AT Protocol
      responses:
        '200':
          description: Feed generator metadata successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedGeneratorDescription'
              example:
                did: 'did:web:atrarium.example.com'
                feeds:
                  - uri: 'at://did:web:atrarium.example.com/app.bsky.feed.generator/community-general'
                    displayName: 'General Discussion'
                    description: 'Main discussion feed for the community'
                  - uri: 'at://did:web:atrarium.example.com/app.bsky.feed.generator/community-tech'
                    displayName: 'Tech Talk'
                    description: 'Technology-focused discussions'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /xrpc/app.bsky.feed.getFeedSkeleton:
    get:
      summary: Get feed skeleton
      description: Returns a skeleton of a feed (post URIs only, not full content). Bluesky AppView fetches full post content separately. (AT Protocol requirement)
      operationId: getFeedSkeleton
      tags:
        - AT Protocol
      parameters:
        - name: feed
          in: query
          required: true
          description: AT-URI of the requested feed
          schema:
            type: string
            pattern: '^at://did:(web|plc):[a-z0-9._:-]+/app\.bsky\.feed\.generator/[a-zA-Z0-9._-]+$'
          example: 'at://did:web:atrarium.example.com/app.bsky.feed.generator/community-general'
        - name: limit
          in: query
          required: false
          description: Maximum number of posts to return (default 50, max 100)
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
          example: 30
        - name: cursor
          in: query
          required: false
          description: Pagination cursor (opaque string returned from previous response)
          schema:
            type: string
          example: '1696291200::bafyreib2rxk3rw6'
      responses:
        '200':
          description: Feed skeleton successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedSkeleton'
              example:
                cursor: '1696290300::bafyreic3sxl4ta7'
                feed:
                  - post: 'at://did:plc:z72i7hdynmk6r22z27h6tvur/app.bsky.feed.post/3k44dddkhc322'
                  - post: 'at://did:plc:ewvi7nxzyoun6zhxrhs64oiz/app.bsky.feed.post/3l42dddabcd12'
                  - post: 'at://did:plc:q6gjnaw2blty4crticxkmujt/app.bsky.feed.post/3k45eeelixy45'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          description: Feed not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XRPCError'
              example:
                error: 'UnknownFeed'
                message: 'Feed not found: at://did:web:atrarium.example.com/app.bsky.feed.generator/nonexistent'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    DIDDocument:
      type: object
      required:
        - '@context'
        - id
        - service
      properties:
        '@context':
          type: array
          items:
            type: string
          description: JSON-LD context
          example: ['https://www.w3.org/ns/did/v1']
        id:
          type: string
          pattern: '^did:(web|plc):[a-z0-9._:-]+$'
          description: DID identifier
          example: 'did:web:atrarium.example.com'
        service:
          type: array
          items:
            $ref: '#/components/schemas/DIDServiceEntry'
          description: Service endpoints
          minItems: 1

    DIDServiceEntry:
      type: object
      required:
        - id
        - type
        - serviceEndpoint
      properties:
        id:
          type: string
          description: Service identifier (fragment)
          example: '#bsky_fg'
        type:
          type: string
          enum: ['BskyFeedGenerator']
          description: Service type
        serviceEndpoint:
          type: string
          format: uri
          description: HTTPS URL of the Feed Generator service
          example: 'https://atrarium.example.com'

    FeedGeneratorDescription:
      type: object
      required:
        - did
        - feeds
      properties:
        did:
          type: string
          pattern: '^did:(web|plc):[a-z0-9._:-]+$'
          description: DID of this Feed Generator
          example: 'did:web:atrarium.example.com'
        feeds:
          type: array
          items:
            $ref: '#/components/schemas/FeedDescriptor'
          description: List of feeds provided by this generator

    FeedDescriptor:
      type: object
      required:
        - uri
      properties:
        uri:
          type: string
          pattern: '^at://did:(web|plc):[a-z0-9._:-]+/app\.bsky\.feed\.generator/[a-zA-Z0-9._-]+$'
          description: AT-URI of the feed
          example: 'at://did:web:atrarium.example.com/app.bsky.feed.generator/community-general'
        displayName:
          type: string
          maxLength: 100
          description: Human-readable feed name
          example: 'General Discussion'
        description:
          type: string
          maxLength: 500
          description: Feed description (plain text or markdown)
          example: 'Main discussion feed for the community'

    FeedSkeleton:
      type: object
      required:
        - feed
      properties:
        cursor:
          type: string
          description: Opaque pagination cursor (format "{timestamp}::{cid}")
          example: '1696290300::bafyreic3sxl4ta7'
        feed:
          type: array
          items:
            $ref: '#/components/schemas/SkeletonFeedPost'
          description: Array of post references

    SkeletonFeedPost:
      type: object
      required:
        - post
      properties:
        post:
          type: string
          pattern: '^at://did:(plc|web):[a-z0-9._:-]+/app\.bsky\.feed\.post/[a-zA-Z0-9]+$'
          description: AT-URI of the post
          example: 'at://did:plc:z72i7hdynmk6r22z27h6tvur/app.bsky.feed.post/3k44dddkhc322'

    XRPCError:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code (e.g., InvalidRequest, UnknownFeed, InternalServerError)
          enum:
            - InvalidRequest
            - UnknownFeed
            - InternalServerError
            - RateLimitExceeded
          example: 'InvalidRequest'
        message:
          type: string
          description: Human-readable error message
          example: 'Invalid feed URI format'

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/XRPCError'
          example:
            error: 'InvalidRequest'
            message: 'Invalid feed URI format'

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/XRPCError'
          example:
            error: 'InternalServerError'
            message: 'An unexpected error occurred'

  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Optional JWT for personalized feeds (Phase 0 not implemented)

security: []
